'use client';

import { useState, useRef, useEffect } from 'react';
import { 
  Bot, 
  Send, 
  Sparkles, 
  HelpCircle, 
  TrendingUp, 
  GraduationCap, 
  CheckCircle2, 
  Circle,
  Map,
  Loader2,
  ChevronRight,
  BookOpen
} from 'lucide-react';

interface Message {
  id: string;
  sender: 'user' | 'assistant';
  text: string;
  roadmap?: {
    title: string;
    nodes: { id: string; label: string; description: string; duration: string; completed: boolean; resources: string[] }[];
  };
}

const frontendNodes = [
  { id: 'fn1', label: 'HTML & CSS Fundamentals', description: 'Master semantic layout, CSS flexbox, grid, and responsive views.', duration: '1 week', completed: true, resources: ['MDN Web Docs', 'CSS-Tricks Guide'] },
  { id: 'fn2', label: 'Modern JavaScript (ES6+)', description: 'Understand closures, promises, async/await, and DOM manipulation.', duration: '2 weeks', completed: false, resources: ['JavaScript.info', 'Eloquent JavaScript'] },
  { id: 'fn3', label: 'React Framework Foundations', description: 'Functional components, hooks (useState, useEffect), and JSX rendering.', duration: '2 weeks', completed: false, resources: ['React Dev Documentation', 'Scrimba React Course'] },
  { id: 'fn4', label: 'Global State & Routing', description: 'Implement Redux Toolkit or Zustand alongside React Router.', duration: '1 week', completed: false, resources: ['Redux Toolkit Docs', 'Zustand GitHub Docs'] },
  { id: 'fn5', label: 'TypeScript & Next.js SSR', description: 'Build statically optimized web applications with typed interfaces.', duration: '2 weeks', completed: false, resources: ['Next.js App Router Tutorial', 'TypeScript Handbook'] }
];

const backendNodes = [
  { id: 'bn1', label: 'Node.js & Express Basics', description: 'Build HTTP servers, handle route parameters, and write middleware.', duration: '2 weeks', completed: false, resources: ['NodeJS guide', 'Express docs'] },
  { id: 'bn2', label: 'Database Design & SQL', description: 'Understand schema models, write subqueries, and manage index files.', duration: '2 weeks', completed: false, resources: ['SQL Tutorial - w3schools', 'PostgreSQL Manual'] },
  { id: 'bn3', label: 'Authentication & JWT security', description: 'Encrypt passwords, sign tokens, and secure router endpoints.', duration: '1 week', completed: false, resources: ['JSON Web Tokens official website', 'bcryptjs guide'] },
  { id: 'bn4', label: 'Docker Containerization', description: 'Write Dockerfiles, build images, and run multi-container networks.', duration: '1 week', completed: false, resources: ['Docker Getting Started Guide'] }
];

export default function AICareerAssistantPage() {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: 'm1',
      sender: 'assistant',
      text: 'Hello! I am your NeoPAT AI Career Copilot. I can help you generate learning roadmaps, answer technical questions, explain industry trends, or recommend courses. What is your career goal?'
    }
  ]);
  const [inputText, setInputText] = useState('');
  const [thinking, setThinking] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to bottom of chats
  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const handleExportRoadmap = (roadmap: { title: string; nodes: any[] }) => {
    let content = `# Study Plan: ${roadmap.title}\n\nGenerated by NeoPAT AI Career Copilot\n\n`;
    roadmap.nodes.forEach((n, idx) => {
      content += `${idx + 1}. [${n.completed ? 'x' : ' '}] ${n.label} (${n.duration})\n`;
      content += `   Description: ${n.description}\n`;
      if (n.resources && n.resources.length > 0) {
        content += `   Resources: ${n.resources.join(', ')}\n`;
      }
      content += `\n`;
    });

    const element = document.createElement("a");
    const file = new Blob([content], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `${roadmap.title.replace(/\s+/g, '_')}_study_plan.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, thinking]);

  const handleSendMessage = (textToSend: string) => {
    if (!textToSend.trim()) return;
    
    const userMsg: Message = {
      id: `user-${Date.now()}`,
      sender: 'user',
      text: textToSend
    };
    
    setMessages(prev => [...prev, userMsg]);
    setInputText('');
    setThinking(true);

    setTimeout(() => {
      let replyText = '';
      let roadmapData = undefined;

      const txt = textToSend.toLowerCase();
      if (txt.includes('frontend') || txt.includes('front end') || txt.includes('front-end')) {
        replyText = 'Here is your custom visual Front-End Software Engineer Roadmap! I have structured the nodes to move you from baseline CSS/HTML to modern Next.js React patterns. Toggle completed items to track your path.';
        roadmapData = {
          title: 'Front-End Engineer Roadmap',
          nodes: frontendNodes
        };
      } else if (txt.includes('backend') || txt.includes('back end') || txt.includes('back-end')) {
        replyText = 'Here is your Backend Software Developer Roadmap. It starts with API structures in Express and proceeds into container systems like Docker. Use this flowchart checklist to manage study sessions.';
        roadmapData = {
          title: 'Backend Developer Roadmap',
          nodes: backendNodes
        };
      } else if (txt.includes('trend') || txt.includes('industry')) {
        replyText = 'Current Software Tech Industry Insights (Q2 2026):\n\n1. **Full-stack React/Next.js and FastAPI**: Highly demanded for rapid product bootstrapping.\n2. **AI Engineer integration**: Knowledge of LLM Prompt Engineering, RAG frameworks (LangChain), and model vector databases is yielding a 40% salary premium.\n3. **PostgreSQL resurgence**: Becoming the standard unified database due to robust JSON support and vector extensions (pgvector).';
      } else {
        replyText = `Based on your request "${textToSend}", I recommend starting with basic data structure practice and mastering JavaScript ES6. Let me know if you would like me to generate a specific roadmap for "Frontend" or "Backend" development!`;
      }

      const assistantMsg: Message = {
        id: `assistant-${Date.now()}`,
        sender: 'assistant',
        text: replyText,
        roadmap: roadmapData
      };

      setMessages(prev => [...prev, assistantMsg]);
      setThinking(false);
    }, 1500);
  };

  const handleNodeToggle = (msgId: string, nodeId: string) => {
    const updated = messages.map(msg => {
      if (msg.id === msgId && msg.roadmap) {
        const updatedNodes = msg.roadmap.nodes.map(n => {
          if (n.id === nodeId) {
            return { ...n, completed: !n.completed };
          }
          return n;
        });
        return {
          ...msg,
          roadmap: {
            ...msg.roadmap,
            nodes: updatedNodes
          }
        };
      }
      return msg;
    });
    setMessages(updated);
  };

  const promptChips = [
    'Generate Frontend Roadmap',
    'Generate Backend Roadmap',
    'What are the latest tech trends?',
    'How should I prepare for interview?'
  ];

  return (
    <div style={{ maxWidth: 950, margin: '0 auto', height: 'calc(100vh - 120px)', display: 'flex', flexDirection: 'column' }} className="animate-fadeInUp">
      
      {/* Top Banner */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, background: 'var(--bg-secondary)', border: '1px solid var(--border)', borderRadius: 12, padding: '12px 16px', marginBottom: 16 }}>
        <div style={{ width: 34, height: 34, background: 'rgba(109,40,217,0.1)', color: 'var(--accent-violet-light)', borderRadius: 8, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <Bot size={18} />
        </div>
        <div>
          <h3 style={{ fontSize: 14, fontWeight: 700 }}>AI Career Advisor</h3>
          <p style={{ fontSize: 11, color: 'var(--text-secondary)' }}>Copilot is ready to analyze roadmaps and explain trends.</p>
        </div>
      </div>

      {/* Messages Scroll Panel */}
      <div style={{
        flex: 1, overflowY: 'auto', border: '1px solid var(--border)', borderRadius: 12,
        background: 'rgba(12, 12, 14, 0.2)', padding: 20, display: 'flex', flexDirection: 'column', gap: 16
      }}>
        {messages.map(msg => {
          const isAssistant = msg.sender === 'assistant';
          return (
            <div key={msg.id} style={{ display: 'flex', gap: 12, alignSelf: isAssistant ? 'flex-start' : 'flex-end', maxWidth: '85%' }}>
              {isAssistant && (
                <div style={{ width: 28, height: 28, background: 'var(--border-bright)', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, color: 'var(--accent-violet-light)' }}>
                  <Bot size={14} />
                </div>
              )}

              <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                {/* Chat bubble text */}
                <div style={{
                  background: isAssistant ? 'rgba(18, 18, 20, 0.85)' : 'var(--accent-violet)',
                  border: isAssistant ? '1px solid var(--border)' : '1px solid transparent',
                  color: '#fff', borderRadius: 12, padding: '12px 16px', fontSize: 13.5, lineHeight: 1.6,
                  whiteSpace: 'pre-wrap'
                }}>
                  {msg.text}
                </div>

                {/* Flowchart Roadmap Render */}
                {msg.roadmap && (
                  <div className="glass animate-fadeInUp" style={{ borderRadius: 10, padding: 18, border: '1px solid var(--border-bright)', background: 'var(--bg-secondary)', marginTop: 4 }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14, borderBottom: '1px solid var(--border)', paddingBottom: 10 }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                        <Map size={14} style={{ color: 'var(--accent-violet-light)' }} />
                        <h4 style={{ fontSize: 13.5, fontWeight: 700 }}>{msg.roadmap.title}</h4>
                      </div>
                      <button
                        onClick={() => handleExportRoadmap(msg.roadmap!)}
                        className="btn-secondary"
                        style={{ padding: '4px 10px', borderRadius: 6, fontSize: 11, gap: 4 }}
                      >
                        <span>Export Plan</span>
                      </button>
                    </div>

                    {/* Flowchart Diagram (Vertical nodes) */}
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 16, position: 'relative', marginTop: 10 }}>
                      
                      {msg.roadmap.nodes.map((node, nodeIdx) => {
                        const isLast = nodeIdx === msg.roadmap!.nodes.length - 1;
                        const isFirstUncompleted = msg.roadmap!.nodes.find(n => !n.completed)?.id === node.id;
                        
                        return (
                          <div key={node.id} style={{ display: 'flex', gap: 14, position: 'relative' }}>
                            {/* Vertical Line Connector */}
                            {!isLast && (
                              <div style={{
                                position: 'absolute', left: 9, top: 22, bottom: -20, width: 2,
                                background: node.completed ? 'var(--accent-emerald)' : 'var(--border)'
                              }} />
                            )}

                            {/* Node Toggle Indicator Icon */}
                            <button
                              onClick={() => handleNodeToggle(msg.id, node.id)}
                              style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, marginTop: 3, zIndex: 10 }}
                            >
                              {node.completed ? (
                                <CheckCircle2 size={20} style={{ color: 'var(--accent-emerald-light)' }} />
                              ) : (
                                <Circle size={20} style={{ color: 'var(--text-muted)' }} />
                              )}
                            </button>

                            {/* Content */}
                            <div style={{ flex: 1 }}>
                              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                                <h5 style={{ 
                                  fontSize: 13, 
                                  fontWeight: 700, 
                                  color: node.completed ? 'var(--text-muted)' : '#fff', 
                                  textDecoration: node.completed ? 'line-through' : 'none',
                                  display: 'flex',
                                  alignItems: 'center',
                                  gap: 6
                                }}>
                                  <span>{node.label}</span>
                                  {isFirstUncompleted && (
                                    <span style={{ 
                                      display: 'inline-flex', alignItems: 'center', gap: 3, 
                                      fontSize: 9, color: 'var(--accent-emerald-light)', background: 'rgba(5,150,105,0.08)',
                                      padding: '1px 6px', borderRadius: 4, fontWeight: 700,
                                      animation: 'pulse 1.5s infinite' 
                                    }}>
                                      <span style={{ width: 4, height: 4, borderRadius: '50%', background: 'var(--accent-emerald-light)' }} />
                                      Active Step
                                    </span>
                                  )}
                                </h5>
                                <span style={{ fontSize: 10, background: 'var(--border)', color: 'var(--text-secondary)', padding: '1px 5px', borderRadius: 4, fontWeight: 600 }}>{node.duration}</span>
                              </div>
                              <p style={{ fontSize: 11.5, color: 'var(--text-secondary)', marginTop: 3 }}>{node.description}</p>
                              
                              {/* Resources */}
                              {node.resources && node.resources.length > 0 && (
                                <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginTop: 6 }}>
                                  {node.resources.map(res => (
                                    <span key={res} style={{ fontSize: 10, color: 'var(--accent-violet-light)', display: 'flex', alignItems: 'center', gap: 2 }}>
                                      <BookOpen size={9} />
                                      <span>{res}</span>
                                    </span>
                                  ))}
                                </div>
                              )}
                            </div>

                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}
              </div>
            </div>
          );
        })}

        {/* Thinking Indicator */}
        {thinking && (
          <div style={{ display: 'flex', gap: 12, alignSelf: 'flex-start' }}>
            <div style={{ width: 28, height: 28, background: 'var(--border-bright)', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--accent-violet-light)' }}>
              <Bot size={14} />
            </div>
            <div style={{ background: 'rgba(18, 18, 20, 0.85)', border: '1px solid var(--border)', borderRadius: 12, padding: '10px 16px', display: 'flex', alignItems: 'center', gap: 8 }}>
              <Loader2 size={13} className="animate-spin-fast" style={{ color: 'var(--accent-violet-light)' }} />
              <span style={{ fontSize: 12, color: 'var(--text-secondary)' }}>Copilot is thinking...</span>
            </div>
          </div>
        )}
        
        <div ref={messagesEndRef} />
      </div>

      {/* Suggested Quick Prompt Chips */}
      <div style={{ display: 'flex', gap: 8, margin: '12px 0 6px', overflowX: 'auto', paddingBottom: 6 }}>
        {promptChips.map(chip => (
          <button
            key={chip}
            onClick={() => handleSendMessage(chip)}
            style={{
              padding: '6px 12px', borderRadius: 20, border: '1px solid var(--border)', background: 'var(--bg-secondary)',
              color: 'var(--text-secondary)', fontSize: 11.5, cursor: 'pointer', whiteSpace: 'nowrap', transition: 'all 0.15s'
            }}
            onMouseOver={(e) => { e.currentTarget.style.borderColor = 'var(--accent-violet-light)'; e.currentTarget.style.color = '#fff'; }}
            onMouseOut={(e) => { e.currentTarget.style.borderColor = 'var(--border)'; e.currentTarget.style.color = 'var(--text-secondary)'; }}
          >
            {chip}
          </button>
        ))}
      </div>

      {/* Input Form Bar */}
      <div style={{ position: 'relative', marginBottom: 8 }}>
        <input
          type="text"
          placeholder="Ask Copilot a question, e.g., 'Generate Frontend Roadmap'..."
          value={inputText}
          onChange={e => setInputText(e.target.value)}
          onKeyDown={e => e.key === 'Enter' && handleSendMessage(inputText)}
          className="input-field"
          style={{ paddingRight: 48, paddingLeft: 16 }}
        />
        <button
          onClick={() => handleSendMessage(inputText)}
          style={{
            position: 'absolute', right: 8, top: 8, background: 'var(--text-primary)', color: 'var(--bg-primary)',
            border: 'none', cursor: 'pointer', width: 28, height: 28, borderRadius: 6, display: 'flex',
            alignItems: 'center', justifyContent: 'center', transition: 'opacity 0.2s'
          }}
          onMouseOver={(e) => (e.currentTarget.style.opacity = '0.8')}
          onMouseOut={(e) => (e.currentTarget.style.opacity = '1')}
        >
          <Send size={13} />
        </button>
      </div>

    </div>
  );
}
